let game= new Game()

let banana = new Sticker("Banana", "/agusgutierrezz-tuttiFrutti/assets/img/banana.jpg")
let bear = new Sticker("Bear", "/agusgutierrezz-tuttiFrutti/assets/img/bear.jpg")
let bee = new Sticker("Bee", "/agusgutierrezz-tuttiFrutti/assets/img/bee.jpg")
let car = new Sticker("Car", "/agusgutierrezz-tuttiFrutti/assets/img/car.jpg")
let carrot = new Sticker("Carrot", "/agusgutierrezz-tuttiFrutti/assets/img/carrot.jpg")
let cow = new Sticker("Cow","/agusgutierrezz-tuttiFrutti/assets/img/cow.jpg")
let dog = new Sticker("Dog","/agusgutierrezz-tuttiFrutti/assets/img/cat.jpg")
let duck = new Sticker("Duck","/agusgutierrezz-tuttiFrutti/assets/img/duck.jpg")
let donut = new Sticker("Donut","/agusgutierrezz-tuttiFrutti/assets/img/donut.jpg")
let pig = new Sticker("Pig","/agusgutierrezz-tuttiFrutti/assets/img/pig.jpg")
let plane = new Sticker("Plane","/agusgutierrezz-tuttiFrutti/assets/img/plane.jpg")
let pizza = new Sticker("Pizza","/agusgutierrezz-tuttiFrutti/assets/img/pizza.jpg")
let letB = new Letter("B","/agusgutierrezz-tuttiFrutti/assets/img/b.jpg")
let letC = new Letter("C","/agusgutierrezz-tuttiFrutti/assets/img/c.jpg")
let letD = new Letter("D","/agusgutierrezz-tuttiFrutti/assets/img/d.jpg")
let letP = new Letter("P","/agusgutierrezz-tuttiFrutti/assets/img/p.jpg")
game.addSticker(cow)
game.addSticker(pizza)
game.addSticker(donut)
game.addSticker(duck)
game.addSticker(car)
game.addSticker(carrot)
game.addSticker(bee)
game.addSticker(bear)
game.addSticker(plane)
game.addSticker(banana)
game.addSticker(dog)
game.addSticker(pig)
game.addLetter(letB)
game.addLetter(letP)
game.addLetter(letC)
game.addLetter(letD)
game.displayScore()
game.displayImages()
// game.startGame()
