let game= new Game()

let banana = new Sticker("Banana", "/assets/img/banana.jpg")
let bear = new Sticker("Bear", "/assets/img/bear.jpg")
let bee = new Sticker("Bee", "/assets/img/bee.jpg")
let car = new Sticker("Car", "/assets/img/car.jpg")
let carrot = new Sticker("Carrot", "/assets/img/carrot.jpg")
let cow = new Sticker("Cow","/assets/img/cow.jpg")
let dog = new Sticker("Dog","/assets/img/cat.jpg")
let duck = new Sticker("Duck","/assets/img/duck.jpg")
let donut = new Sticker("Donut","/assets/img/donut.jpg")
let pig = new Sticker("Pig","/assets/img/pig.jpg")
let plane = new Sticker("Plane","/assets/img/plane.jpg")
let pizza = new Sticker("Pizza","/assets/img/pizza.jpg")
let letB = new Letter("b","/assets/img/b.jpg")
let letC = new Letter("c","/assets/img/c.jpg")
let letD = new Letter("d","/assets/img/d.jpg")
let letP = new Letter("p","/assets/img/p.jpg")
game.addSticker(cow)
game.addSticker(pizza)
game.addSticker(donut)
game.addSticker(duck)
game.addSticker(car)
game.addSticker(carrot)
game.addSticker(bee)
game.addSticker(bear)
game.addSticker(plane)
game.addSticker(banana)
game.addSticker(dog)
game.addSticker(pig)
game.addLetter(letB)
game.addLetter(letP)
game.addLetter(letC)
game.addLetter(letD)
game.displayImages()
game.displayLetter()
